In [ ]:
import pandas as pd
import numpy as np

In [2]:
file_path = "../../DATA EXPLORER CONTEST/Data - 12ndMar/6.1 (his) financialreport_balancesheet_FPT_CMG_processed.csv"

dataframe = pd.read_csv(file_path)

dataframe.head()

,Indicator,StockID,6M_2023,6M_2024,9M_2023,9M_2024,Q1_2023,Q1_2024,Q2_2023,Q2_2024,Q3_2023,Q3_2024,Q4_2023,Q4_2024,Y_2023,Y_2024
0,- Cổ phiếu phổ thông có quyền biểu quyết\n411a,CMG,"1,505,960,320,000","1,904,392,960,000","1,900,269,960,000","1,903,974,960,000","1,505,960,320,000","1,904,392,960,000","1,505,960,320,000","1,904,392,960,000","1,900,269,960,000","1,903,974,960,000","1,900,269,960,000",NaN,"1,900,269,960,000",NaN
1,- Cổ phiếu phổ thông có quyền biểu quyết\n411a,FPT,"11,043,316,220,000","14,604,480,660,000","12,699,688,750,000","14,604,480,660,000","10,970,265,720,000","12,699,688,750,000","11,043,316,220,000","14,604,480,660,000","12,699,688,750,000","14,604,480,660,000","12,699,688,750,000","14,710,691,830,000","12,699,688,750,000","14,710,691,830,000"
2,- Giá trị hao mòn lũy kế\n223,CMG,"-1,577,566,941,383","-1,886,773,746,201","-1,655,226,032,606","-1,972,024,039,112","-1,513,783,100,366","-1,810,449,040,895","-1,577,558,303,535","-1,895,977,157,084","-1,655,226,032,606","-1,972,024,039,112","-1,734,759,159,367",NaN,"-1,732,114,441,724",NaN
3,- Giá trị hao mòn lũy kế\n223,FPT,"-9,109,849,933,394","-10,798,956,932,818","-9,539,916,194,703","-11,261,187,491,234","-8,728,063,268,763","-10,351,316,034,547","-9,139,679,844,094","-10,798,956,932,818","-9,539,916,194,703","-11,261,187,491,234","-9,906,952,653,021","-11,683,165,704,793","-9,906,845,402,941","-11,683,165,704,793"
4,- Giá trị hao mòn lũy kế\n226,FPT,"-3,878,313,753","-4,386,536,239","-3,587,478,607","-3,607,403,617","-24,915,388,622","-4,197,599,404","-29,013,930,078","-4,386,536,239","-3,587,478,607","-3,607,403,617","-4,013,832,181","-3,673,326,424","-4,013,832,181","-3,673,326,424"

In [3]:
dataframe.drop(columns=['6M_2023','6M_2024','9M_2023','9M_2024','Y_2023','Y_2024'], inplace=True)
dataframe

,Indicator,StockID,Q1_2023,Q1_2024,Q2_2023,Q2_2024,Q3_2023,Q3_2024,Q4_2023,Q4_2024
0,- Cổ phiếu phổ thông có quyền biểu quyết\n411a,CMG,"1,505,960,320,000","1,904,392,960,000","1,505,960,320,000","1,904,392,960,000","1,900,269,960,000","1,903,974,960,000","1,900,269,960,000",NaN
1,- Cổ phiếu phổ thông có quyền biểu quyết\n411a,FPT,"10,970,265,720,000","12,699,688,750,000","11,043,316,220,000","14,604,480,660,000","12,699,688,750,000","14,604,480,660,000","12,699,688,750,000","14,710,691,830,000"
2,- Giá trị hao mòn lũy kế\n223,CMG,"-1,513,783,100,366","-1,810,449,040,895","-1,577,558,303,535","-1,895,977,157,084","-1,655,226,032,606","-1,972,024,039,112","-1,734,759,159,367",NaN
3,- Giá trị hao mòn lũy kế\n223,FPT,"-8,728,063,268,763","-10,351,316,034,547","-9,139,679,844,094","-10,798,956,932,818","-9,539,916,194,703","-11,261,187,491,234","-9,906,952,653,021","-11,683,165,704,793"
4,- Giá trị hao mòn lũy kế\n226,FPT,"-24,915,388,622","-4,197,599,404","-29,013,930,078","-4,386,536,239","-3,587,478,607","-3,607,403,617","-4,013,832,181","-3,673,326,424"
...,...,...,...,...,...,...,...,...,...,...
267,V. Đầu tư tài chính dài hạn\n250,FPT,"3,257,209,895,051","3,415,559,155,234","3,045,169,826,409","3,095,902,850,581","3,223,296,628,954","3,214,141,461,080","3,367,402,312,269","3,319,014,817,651"
268,VI. Tài sản dài hạn khác\n260,CMG,"372,896,263,050","460,529,530,005","364,961,956,402","416,436,745,932","386,830,452,415","422,677,746,724","385,154,433,015",NaN
269,VI. Tài sản dài hạn khác\n260,FPT,"4,512,159,868,725","5,366,724,357,153","4,501,685,335,332","5,241,548,882,861","4,529,333,425,055","5,501,511,121,171","5,042,420,397,778","5,485,644,852,548"
270,Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi...,CMG,"-1,736,442,213",NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi...,FPT,"3,163,289,455","-37,407,398,624",NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Lọc theo điều kiện Indicator và StockID
filtered_df = dataframe[
    (dataframe['Indicator'].str.contains('Lợi nhuận sau thuế của cổ đông của Công ty mẹ', regex=True)) &
    (dataframe['StockID'] == 'FPT')
]
filtered_df

,Indicator,StockID,Q1_2023,Q1_2024,Q2_2023,Q2_2024,Q3_2023,Q3_2024,Q4_2023,Q4_2024
236,Lợi nhuận sau thuế của cổ đông của Công ty mẹ,FPT,"1,493,562,580,890","1,798,030,863,528","1,509,219,531,243","1,873,814,750,772","1,739,340,360,244","2,088,852,212,408","1,728,399,961,335","2,086,993,221,115"

In [5]:
# Tạo một danh sách các ngày từ 26/3/2024 đến 12/3/2025
date_range = pd.date_range(start='2024-03-26', end='2025-03-12')

# Tạo dataframe chỉ chứa cột ngày tháng và khởi tạo cột 'Lợi nhuận' với giá trị NaN
bang_loi_nhuan = pd.DataFrame({'Date': date_range})
bang_loi_nhuan['Loi nhuan'] = np.nan

# Lặp qua các hàng trong filtered_df
for item in filtered_df.columns:
    if item == 'Q4_2023':  # Kiểm tra nếu cột là 'Q4_2023'
        for i, date in enumerate(bang_loi_nhuan['Date']):
            # Kiểm tra điều kiện ngày tháng
            if 1 <= date.month <= 3 and 1 <= date.day <= 31 and date.year == 2024:
                bang_loi_nhuan.loc[i, 'Loi nhuan'] = filtered_df[item].values[0]
    if item == 'Q1_2024':  # Kiểm tra nếu cột là 'Q1_2024'
        for i, date in enumerate(bang_loi_nhuan['Date']):
            # Kiểm tra điều kiện ngày tháng
            if 4 <= date.month <= 6 and 1 <= date.day <= 31 and date.year == 2024:
                bang_loi_nhuan.loc[i, 'Loi nhuan'] = filtered_df[item].values[0]  # Gán giá trị vào cột 'Lợi nhuận'
    elif item == 'Q2_2024':
        for i, date in enumerate(bang_loi_nhuan['Date']):
            # Kiểm tra điều kiện ngày tháng
            if 7 <= date.month <= 9 and 1 <= date.day <= 31 and date.year == 2024:
                bang_loi_nhuan.loc[i, 'Loi nhuan'] = filtered_df[item].values[0]
    elif item == 'Q3_2024':
        for i, date in enumerate(bang_loi_nhuan['Date']):
            # Kiểm tra điều kiện ngày tháng
            if 10 <= date.month <= 12 and 1 <= date.day <= 31 and date.year == 2024:
                bang_loi_nhuan.loc[i, 'Loi nhuan'] = filtered_df[item].values[0]
    elif item == 'Q4_2024':
        for i, date in enumerate(bang_loi_nhuan['Date']):
            # Kiểm tra điều kiện ngày tháng
            if 1 <= date.month <= 3 and 1 <= date.day <= 31 and date.year == 2025:
                bang_loi_nhuan.loc[i, 'Loi nhuan'] = filtered_df[item].values[0]

# Hiển thị kết quả
bang_loi_nhuan

C:\Users\Dell\AppData\Local\Temp\ipykernel_14656\1424352126.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1,798,030,863,528' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  bang_loi_nhuan.loc[i, 'Loi nhuan'] = filtered_df[item].values[0]  # Gán giá trị vào cột 'Lợi nhuận'

          Date          Loi nhuan
0   2024-03-26  1,728,399,961,335
1   2024-03-27  1,728,399,961,335
2   2024-03-28  1,728,399,961,335
3   2024-03-29  1,728,399,961,335
4   2024-03-30  1,728,399,961,335
..         ...                ...
347 2025-03-08  2,086,993,221,115
348 2025-03-09  2,086,993,221,115
349 2025-03-10  2,086,993,221,115
350 2025-03-11  2,086,993,221,115
351 2025-03-12  2,086,993,221,115

[352 rows x 2 columns]

In [ ]:
# Xuất kết quả ra file CSV
bang_loi_nhuan.to_csv('../../DATA EXPLORER CONTEST/Preprocessed_Data/bang_loi_nhuan.csv', index=False)